// Generated by CoffeeScript 1.9.3
(function() {
  var CommonState, Descriptor, EffectLayer;

  Descriptor = require('../../descriptor.coffee');

  EffectLayer = require('../effect_layer_info.coffee');

  module.exports = CommonState = (function() {
    CommonState.shouldParse = function(key) {
      return key === 'cmnS';
    };

    function CommonState(file, size) {
      this.file = this.version = null;
      this.visible = null;
    }

    CommonState.prototype.parse = function() {
      this.version = this.file.readInt();
      this.visible = this.file.readByte();
      return this.file.seek(2, true);
    };

    CommonState.prototype["export"] = function() {
      return {
        version: this.version,
        visible: this.visible
      };
    };

    return CommonState;

  })();

}).call(this);
