// Generated by CoffeeScript 1.9.3
(function() {
  var Descriptor, EffectLayer, InnerShadow;

  Descriptor = require('../../descriptor.coffee');

  EffectLayer = require('../effect_layer_info.coffee');

  module.exports = InnerShadow = (function() {
    var BLEND_MODES;

    InnerShadow.shouldParse = function(key) {
      return key === 'isdw';
    };

    BLEND_MODES = {
      norm: 'normal',
      dark: 'darken',
      lite: 'lighten',
      hue: 'hue',
      sat: 'saturation',
      colr: 'color',
      lum: 'luminosity',
      mul: 'multiply',
      scrn: 'screen',
      diss: 'dissolve',
      over: 'overlay',
      hLit: 'hard_light',
      sLit: 'soft_light',
      diff: 'difference',
      smud: 'exclusion',
      div: 'color_dodge',
      idiv: 'color_burn',
      lbrn: 'linear_burn',
      lddg: 'linear_dodge',
      vLit: 'vivid_light',
      lLit: 'linear_light',
      pLit: 'pin_light',
      hMix: 'hard_mix',
      pass: 'passthru',
      dkCl: 'darker_color',
      lgCl: 'lighter_color',
      fsub: 'subtract',
      fdiv: 'divide'
    };

    function InnerShadow(file, size) {
      this.file = file;
      this.version = null;
      this.blur = null;
      this.intensity = null;
      this.angle = null;
      this.distance = null;
      this.color = null;
      this.blendmode = null;
      this.enbled = null;
      this.angleInAll = null;
      this.opacity = null;
      this.nativeColor = null;
      this.end = this.file.tell() + size;
    }

    InnerShadow.prototype.parse = function() {
      this.version = this.file.readInt();
      this.blur = this.file.readInt() / 65536;
      this.intensity = this.file.readInt() / 65536;
      this.angle = this.file.readInt() / 65536;
      this.distance = this.file.readInt() / 65536;
      this.color = this.file.readSpaceColor();
      this.file.seek(4, true);
      this.blendmode = BLEND_MODES[this.file.readString(4).trim()];
      this.enbled = this.file.readBoolean();
      this.angleInAll = this.file.readByte();
      this.opacity = Math.round(this.file.readByte() / 2.55);
      this.nativeColor = this.file.readSpaceColor();
      return this.file.seek(this.end);
    };

    InnerShadow.prototype["export"] = function() {
      return {
        version: this.version,
        blur: this.blur,
        intensity: this.intensity,
        angle: this.angle,
        distance: this.distance,
        color: this.color,
        blendmode: this.blendmode,
        enbled: this.enbled,
        angleInAll: this.angleInAll,
        opacity: this.opacity,
        nativeColor: this.nativeColor
      };
    };

    return InnerShadow;

  })();

}).call(this);
