// Generated by CoffeeScript 1.10.0
var Convolution, Module;

Module = require('coffeescript-module').Module;

Convolution = require('./convolution.coffee');

module.exports = function(pixels) {
  var divider, operator;
  divider = 16;
  operator = [1 / divider, 2 / divider, 1 / divider, 2 / divider, 4 / divider, 2 / divider, 1 / divider, 2 / divider, 1 / divider];
  return Convolution(pixels, operator);
};
