// Generated by CoffeeScript 1.9.3
(function() {
  var Renderer;

  Renderer = require('../renderer.coffee');

  module.exports = {
    toPng: function() {
      return this.layer.image.toPng();
    },
    saveAsPng: function(output) {
      var renderer;
      renderer = new Renderer(this, {});
      return renderer.render(output);
    }
  };

}).call(this);
